### ISSUE TITLE
spaces or tabs - pick one

### ISSUE THREAD

**Issue by zimeon** [iiif-prezi/iiif-prezi#31]
@zimeon from #30: We should settle on spaces or tabs for indent and use consistently (perhaps even with a tool to check?). Out of habit I "fixed" some of this code to use spaces but then found it was almost all tabs and changed it back.

@azaroth42: I have a bad habit of swapping between emacs and sublime2. I think there's a PEP that most(?) editors read to define the indentation? So long as I can continue to swap, and the editors do the right thing, I don't mind. --> issue?

**Comment by zimeon** [comment]
PEP8 says spaces: https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces but no comment about editor magic

**Comment by azaroth42** [comment]
If you have magic to convert tabs to 4 spaces, magic away.

sublime: https://www.sublimetext.com/docs/2/indentation.html
emacs: https://www.emacswiki.org/emacs/NoTabs
