### ISSUE TITLE
Drop python 2.6 support, use current Pillow

### ISSUE THREAD

**Issue by zimeon** [iiif-prezi/iiif-prezi#45]
Can we now drop support for Python 2.6? I think is would be OK to keep python 2.7, 3.3 and up. That would allow us to ditch the pin to Pillow 3.4.2.

We have already done this with the Image API validator (https://github.com/IIIF/image-validator/issues/50)

@azaroth42 ?

**Comment by hugovk** [comment]
Pillow has also dropped support for Python 3.3 which is also EOL and generally even less used than 2.6. 

https://pillow.readthedocs.io/en/latest/installation.html#notes

So I propose Python 2.7 and 3.4+.

**Comment by hugovk** [comment]
Please see PR #47.
