### ISSUE TITLE
Pillow dependency

### ISSUE THREAD

**Issue by scossu** [iiif-prezi/iiif-prezi#54]
I have 2 questions/suggestions about the dependency on Pillow: 

1. The `iiif-prezi` package seems to depend on a quite old version of Pillow: 

```
$ pip install --upgrade pillow==4.0

[...]
ERROR: iiif-prezi 0.2.9 has requirement Pillow<4.0.0,>=3.2.0, but you'll have pillow 4.0.0 which is incompatible.
[...]
```

The current Pillow version is 6.x. Is there a reason not to update the dependency? 

2. From looking at the code, the only reason for having Pillow is here: https://github.com/iiif-prezi/iiif-prezi/blob/master/iiif_prezi/factory.py#L1352-L1355 

If you don't need to read or manipulate pixel data, Pillow seems overkill. Something like [piexif](https://pypi.org/project/piexif/) is probably far more lightweight in terms of installation, dependency management and runtime performance. 

I can submit a pull request replacing the dependency from Pillow and/or Imagemagick with Piexif if that sounds like a good idea.

**Comment by zimeon** [comment]
@scossu -- yes please! The tie to old Pillow is a rather dated expedient! I don't have a sense of which of the two options you propose is better -- we want to optimize for clean code + easy maintenance I think.

**Comment by zimeon** [comment]
This was resolved a long time ago in https://github.com/iiif-prezi/iiif-prezi/commit/0fbf417ebf8a8d56336a7ca7b5f17bbfb34aa0a5
